server:
  port: 9091

spring:
  application:
    name: proxy-kafka-jms

artemis:
  broker-password: ${JMS_BROKER_PASSWORD:admin}
  broker-url: ${JMS_BROKER_URL:tcp://127.0.0.1:61616}
  broker-username: ${JMS_BROKER_USERNAME:admin}

logging:
  level:
    ROOT: DEBUG

camel:
  springboot:
    main-run-controller: true
  component:
    activemq:
      error-handler-logging-level: INFO
      error-handler-log-stack-trace: true
      broker-url: ${JMS_BROKER_URL:tcp://127.0.0.1:61616}
      password: ${JMS_BROKER_PASSWORD:admin}
      trust-all-packages: true
      username: ${JMS_BROKER_USERNAME:admin}
      lazy-create-transaction-manager: true
      accept-messages-while-stopping: true
      transacted: true
      connection-factory: ActiveMQConnectionFactory
      transaction-manager: JmsTransactionManager
      acknowledgement-mode-name: CLIENT_ACKNOWLEDGE
    kafka:
      schema-registry-u-r-l: ${KAFKA_SCHEMA_REGISTRY_URL:http://127.0.0.1:8081}
#      security-protocol: SASL_PLAINTEXT
#      sasl-mechanism: PLAIN
#      sasl-jaas-config: ${KAFKA_SASL_JAAS:org.apache.kafka.common.security.plain.PlainLoginModule required username=admin password=admin-secret;}
      bridge-error-handler: true
      brokers: ${KAFKA_BROKER_URL:127.0.0.1:9092}
      request-required-acks: all
      enable-idempotence: true
      max-in-flight-request: 1
      retries: 5
      auto-commit-enable: false
      auto-offset-reset: earliest
      group-id: proxy-kafka-jms
      allow-manual-commit: true
      break-on-first-error: true
      valueSerializer: io.cloudevents.kafka.CloudEventSerializer
      valueDeserializer : io.cloudevents.kafka.CloudEventDeserializer
#      valueSerializer: ma.cdgk.integration.camel.serde.KafkaJmsProxySerializer
#      valueDeserializer: ma.cdgk.integration.camel.serde.KafkaJmsProxyDeserializer

source-destination-config:
  jmsToKafkaQueueTopicPairs:
    - queue: jsonSourceQueue
      topic: topic1FromJsonSourceQueue
      queueFormat: json
      queueMappingClass: ma.cdgk.integration.model.Event #Eventjson
      normalizer: ma.cdgk.integration.normalizer.AmortissementCreditNormalizer
      topicMappingClass: ma.cdgk.integration.model.Event #avroType #tjr
      topicFormat: CloudEvent #tjr
      #Service mapping
      source-systeme: calyps #tjr
      destination-source: oly
      mongo-journaly: true #tjr
#    - queue: xmlSourceQueue
#      topic: topic1FromXMLSourceQueue
#      topicFormat: CloudEvent #tjr
#      queueFormat: xml
#      topicMappingClass: Event2 # avroType #tjr
#      queueMappingClass: Event
#      #Service mapping
#      source-systeme: calyps #tjr
#      destination-source: oly
#      mongo-journaly: true #tjr

#  kafkaToJmsQueueTopicPairs:
#    - topic: topic1FromXMLSourceQueue_
#      queue: xmlReceiverQueue
#      topicFormat: json #should be always CloudEvent ?
#      queueFormat: xml
#      topicMappingClass: Event
#      queueMappingClass: Event
#      #Service mapping
#      source-systeme: oly
#      destination-source: test
#      mongo-journaly: false
#    - topic: topic1FromJsonSourceQueue
#      queue: jsonReceiverQueue
#      topicFormat: json
#      queueFormat: json
#      topicMappingClass: Event
#      queueMappingClass: Event
#      #Service mapping
#      source-systeme: oly
#      destination-source: test
#      mongo-journaly: false
#todo: add conf event source

service-config:
  systeme-source: calypso


#      topicFormat: json , cloudEvent ,avro
#      queueFormat: json ,xml
